### ISSUE TITLE
SpriteAnimator.cs Line 68 There's a Debug Message and you cannot disable.

### ISSUE THREAD

**Issue by OscarLeif** [GabrielBigardi/Unity-2D-Sprite-Animator#2]
this line can be found

### Debug.Log(SpriteAnimationHelper.GetCurrentFrame());

There's no option or settings to disable the message....maybe a bool  "DebugMessage"
### if(DebugMessage){ Debug.Log(SpriteAnimationHelper.GetCurrentFrame());}

This generates a lot of GC.

**Comment by GabrielBigardi** [comment]
Hi, sorry about that and for the late answer, i'm gonna be fixing it right now
