### ISSUE TITLE
Add assembly definition to make import via git URL possibe

### ISSUE THREAD

**Issue by quangamedev** [GabrielBigardi/Unity-2D-Sprite-Animator#5]
Hi, adding the package via git URL does not work because your repository does not have an assembly definition.
I cannot create Sprite Animation assets nor add any related components to GameObjects when importing this way.
Warnings:
![image](https://github.com/GabrielBigardi/Unity-2D-Sprite-Animator/assets/68118284/6e9db8e2-3830-46bd-8ab0-cc3c240510df)

Please add an assembly definition file to this reposiory. This is a common practice used in similar packages.
Example:
![image](https://github.com/GabrielBigardi/Unity-2D-Sprite-Animator/assets/68118284/c67c37d0-2764-4887-81e6-fdb2b146b0fc)

**Comment by GabrielBigardi** [comment]
Hi, sorry for the delay, it used to have an assembly definition, i removed it because importing it this way makes it impossible to make changes to the package.
I will be adding it back soon
