### ISSUE TITLE
Compiler error in folder Editor

### ISSUE THREAD

**Issue by MaansenV** [GabrielBigardi/Unity-2D-Sprite-Animator#7]
![NVIDIA_Share_Bg1UVxDFtL](https://github.com/GabrielBigardi/Unity-2D-Sprite-Animator/assets/70063959/3c94c154-0744-490f-a2d0-ca4a2476192d)

Im getting compiler error

**Comment by GabrielBigardi** [comment]
Hi, that's related to some weird bug on Assembly Definitions in Unity, i recommend cloning the repository and importing only the folders "Editor"/"Runtime"
